# Generated by Django 2.0.2 on 2018-06-08 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
