# Generated by Django 2.0.2 on 2018-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180608_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
