# Generated by Django 2.0.2 on 2018-06-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='job_name',
        ),
    ]
