# Generated by Django 2.0.2 on 2018-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180618_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_name',
        ),
    ]
